name: johnryan
favicon: null
layout_spectrum: 0.887061
typography_spectrum: 0.323464
title: John Ryan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1E5167'
    - '#50A8A8'
    - '#40A0C8'
    - '#50A8D0'
  brandStrength: 0.461584
  lightness: 0.675438
  saturation: 0.801256
  rhythmicContrast: 0.502192
purpose: []
