analytics: {}
color:
  brandColors:
    - '#000000'
    - '#1E5167'
    - '#50A8A8'
    - '#40A0C8'
    - '#50A8D0'
  brandStrength: 0.461584
  lightness: 0.675438
  rhythmicContrast: 0.502192
  saturation: 0.801256
cta: {}
layout_spectrum: 0.887061
name: johnryan
opengraph: {}
purpose: []
typography_spectrum: 0.323464
